### ISSUE TITLE
Invalid bytecode in file

### ISSUE THREAD

**Issue by NaliFinance** [MrSpike63/vanity-eth-address#4]
$ ./x86_64_linux.bin -d 0 -d 1 -d 2 -d 3 -d 4 -d 5 -lz 10 -w 20 --contract3 --bytecode bytecode.txt --deployer-address 0x9fBB3DF7C40Da2e5A0dE984fFE2CCB7C47cd0ABf --address 0xc5067d91d18cd4446654e516b0c175c7f68a6894

i don't know why it keeps telling invalid bytecode in file, i tried the 60xxxxx bytecode from remix and 73xxxxxx deployed bytecode without success, tried also to add 0x at the beginning.. 

What format is expecting for contract3 vanity address gen?

**Comment by MrSpike63** [comment]
Are you adding a newline by any chance? It's either that or the bytecode being too long somehow.

**Comment by NaliFinance** [comment]
yep, sorry, i came here after i found that bytes were odd.. i leave this for newcomers :)

tr -d "\n\r" < bytecode.txt > bytecode.txt

Thank you very much!
