### ISSUE TITLE
Profanity Address Hack

### ISSUE THREAD

**Issue by crypt0inf0** [MrSpike63/vanity-eth-address#6]
I hear about the https://medium.com/coinmonks/the-profanity-address-hack-how-are-vanity-addresses-generated-cce40ba5ed39 Is it possible to generate the same address using this generator?

**Comment by MrSpike63** [comment]
If you're asking if this has the same vulnerability, then as far as I am aware, no. The initial private key is obtained from either BCryptGenRandom or /dev/urandom.
