### ISSUE TITLE
Regarding the ETH private keys and addresses printed for each Elapsed

### ISSUE THREAD

**Issue by onionscode** [MrSpike63/vanity-eth-address#9]
Hello, I found an issue when testing with your program. The running parameters are: ./main --zeros --device 0. I noticed that as Elapsed: increases, the addresses and private keys printed by the program become fewer and fewer. When running 200 iterations, some of the Elapsed values don't print the expected data, but DEVICE 0: 584.19M/s continues to display a lot of information. Am I using it incorrectly?

 ./main --zeros --device 0
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4e8544ac4 Address: 0x1aba00754668e52e56e5009ff4790000e6cf00ea
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4e2328fdb Address: 0xd8d1bc000da2b42661c8000031400070efff00ee
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b7eff0a24f Address: 0xd400411ee300630c4e5ae1842cbe000000675a97
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4dfc9a4ae Address: 0xd079b3c2b8000f8e6b00005875aba38f4500f900
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4df56e827 Address: 0x006d97000082128700d48f690be30012ca55ef13
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4de418fca Address: 0x00c30544fbcd3500380069b847ceae2d00a5008d
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4dd7507ae Address: 0x872676000091f5bd0046ffff6395aee00020f700
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b7f32aa166 Address: 0xeb00f78900bfd90023e8e5001acd66290026645c
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4d814564f Address: 0x2787e25507ee3f0004f817008c5d00ff0000f5dc
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4d78fcd75 Address: 0x760000f1a7a85017a700b0ac00aa2f3500f2a017
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b7fa9de9cb Address: 0x0800e71fb6feb102530a0000af398c00002cda08
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4d55fd882 Address: 0xbad316e91100806f7c776c4a0000000070f62c3a
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4d1248c0b Address: 0x8bf25abe002dd47d008c7760926d5a0028090000
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4ce329eaa Address: 0x2f54465a58296800bf00009e1292103800d600d4
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b80277cc25 Address: 0x2c004b2d04003d0c4900e80031ac1200e2a9d810
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4ccbff1a5 Address: 0xc450660000f8ff5c0c015f162e00fde0750000a1
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4cba90aa9 Address: 0xd8b8c3000900007673129ec0007000c0b247418b
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4c803b277 Address: 0x00000000e09419730288008de2591b261ac34ca3
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b8095f2d8c Address: 0x69000046ddbb668f00fda1ca106e22e600dc5000
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4c2978a1c Address: 0x008cd3f100a0003193003bd7bf8e7d37bc331000
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4bdaf6bec Address: 0x764da4822eca2d59db7d3400005c0000bb2400af
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4bc73fde3 Address: 0x00e700a250c35478572864006c39b75b00005a0e
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4b60bb3fe Address: 0x9a0932ac2d0000c50046c68d88cafbc5ee0000c1
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4b41e3f37 Address: 0x3ece4ad880990000009e48a087004ce75056dd00
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b81eb50cd6 Address: 0x50dc900031005c00dd3200f5c93aefd4150b005e
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4b0a28351 Address: 0xf6f600860091a3bd0764363eb5e50000fa00b9a2
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b82059f353 Address: 0xd8a5c09c8997d4000000636590a70000ef6d43b1
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b8248ca29e Address: 0x68b3217c28f200c0008482db00900000631b2149
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4aa61a184 Address: 0x336eeee000783d21fe009523305b002d00bc0060
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b8261569b2 Address: 0x89d6530f120085ae006500490e00931f2c851f00
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b8268097ce Address: 0x9d22860000393898b18fc6005a9fa63e1d007400
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b829f41dd4 Address: 0xd6323f004a9b2000e3624b000497003cc3e6e200
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4a52efea5 Address: 0x26b4c207810000cd777aa2b50eab00003b58c700
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b82b608e66 Address: 0x0e11d80000946091a22215c900791da10050ee00
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b82c11afd1 Address: 0xe7c454b1c4260012ecec71009500e79a000088c8
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b82d9ed6a9 Address: 0xa5d298ceee69d35893ceca00d20000808700009d
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4a0db4c9d Address: 0x160032d0005600bb5b18007d8224b5f0b000210a
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b8301c0929 Address: 0xb6e3a1535f027f006400ec389296fde700ff0000
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d496e1beea Address: 0xce00bde7a60000a061f400f7d011922b00f9740f
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b8394ac5cb Address: 0xde00c901004fbd0048ac006a0aa3003833698fce
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d493fc634f Address: 0x00b100d56200eac958da1e84ff544230ddbf0000
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b83d1c7452 Address: 0x009a00003a006d8ade009c9c634ddc064cb73f0f
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d48fcb22a6 Address: 0x3b1876278f98d8e60043880000cfda3800004e6a
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b841696cd8 Address: 0x34159d00c4aab2a42d630000507a2a5388002e00
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d48ece6e9d Address: 0x37dd31bdc74d3600732d5c23a8005e00009a8600
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b84246c67e Address: 0x5abf8656410089005a23790055359b00e5100001
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b84248be7f Address: 0xf49f40cd9be800001aa0fa650f1700c20000f91f
Elapsed: 000008 Score: 05 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b844b85d0c Address: 0xa2003400eb87a8d1006006410000b12f6709f6b7
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d48a2a0300 Address: 0xe076a10000a2aa5e0000f25fbd8c4a00756be00e
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d48650a7c6 Address: 0x007579004030ce0000c48e940034593c9a6fcb4e
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d47dd3cce7 Address: 0x4ea914005d4c00723ba4008c75005fc88800ce84
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d47cec4024 Address: 0x00f7dd0087220055dd004941245f254f00157e27
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d47bb16f59 Address: 0x00000000576d86844b81dadab33c2cf79e4b00e7
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d478dbfda0 Address: 0xd49488caf4000000de668b4f93ca11004500a409
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d4720fa391 Address: 0xbb5700ca62002e00a7ea98008e3174de88060024
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d46dcdd96f Address: 0x09d9d400652a3060c59e00ea00434f3100c00012
Elapsed: 000008 Score: 05 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d46b8b5cb0 Address: 0x55597136cac20000001d2e6eb8509c00005d25f3
Elapsed: 000015 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b8b2fec73d Address: 0x4441ff4000007700bd7d80330066190017e0c800
Elapsed: 000022 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9b9011abb49 Address: 0xb70088c500b60000244400f77543ceb363001da7
Elapsed: 000037 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9ba6320ed91 Address: 0x653a0000946a6dc20090005100c6ca5100c77fa6
Elapsed: 000051 Score: 06 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d1e5d223ab Address: 0x00531daaa100cfdc6deb2000003573904400dc00
Elapsed: 000051 Score: 06 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d1d03db1ed Address: 0xc3ca00624d6d00b60019b883007d009c5971bc00
Elapsed: 000058 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9bb6bdbedd0 Address: 0x21490038d016c50e0026c00032c60b0000897000
Elapsed: 000073 Score: 06 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84d062be593d Address: 0x3f22929200004f720c7b0000887d893e2f6d0000
Elapsed: 000080 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9bd4b193be8 Address: 0x251c09e6b0d357b1e1008d6700f300c800900000
Elapsed: 000088 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9bd907891fb Address: 0x9600006e54d400701200bde9003e539fe2470078
Elapsed: 000117 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9bf86d09fd7 Address: 0x2b000076ff00db0b5550175ac0fe90a700ca0000
Elapsed: 000117 Score: 06 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84ccf5485266 Address: 0x00401500d0e48ff8002d0b1b00325b0028311400
Elapsed: 000146 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9c167b65238 Address: 0x000000ae00cfaafb75350057a47256f88ed300d2
Elapsed: 000146 Score: 06 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84caed97debc Address: 0x1d006f00af35f0e9a30096510087000090107399
Elapsed: 000161 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9c2bcda8818 Address: 0x0000c20086f4f900aee59239690900fd9e700100
Elapsed: 000183 Score: 06 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84c87a8b6366 Address: 0x00e11e5d00ac7d8a5904a30000006a4f13090023
Elapsed: 000190 Score: 06 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84c8544515ee Address: 0x00e56d8259a4d9007b360000763c85f4d5dc0000
Elapsed: 000190 Score: 06 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84c83651d60e Address: 0x00130032d38db50000edc18f7f35004300efb536
Elapsed: 000198 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9c506000a73 Address: 0x29dd1a00005e0d7298f1000000e2530044c9c3fa
Elapsed: 000205 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9c59ddaeb42 Address: 0x53dd331612f2000026a9047397c700a00000004a
Elapsed: 000227 Score: 06 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84c56fa962d7 Address: 0x8b00c4120012da56f9d61bf2410086004200008d
Elapsed: 000234 Score: 06 Private Key: 0x91e72c4b0e4496ccf4f0265ae0ce61ac6760cbda342eac8c422b84c51b664752 Address: 0x6253407500f44200350200fabb0000008d81ccdf
Elapsed: 000242 Score: 06 Private Key: 0x6e18d3b4f1bb69330b0fd9a51f319e52534e110c7b19f3af7da6d9c834a60092 Address: 0x008b563084149900bc0000ea7dd600edb9a4da00
Total: 584.19M/s  DEVICE 0: 584.19M/s

**Comment by MrSpike63** [comment]
Addresses are only printed if their score is greater than or equal to the highest score that has been found so far. In your case, it started by printing addresses with a score of at least 5, and once it found an address with a score of 6, changed the threshold to 6.

**Comment by onionscode** [comment]
Oh, oh, thank you!
